# Generated by Django 6.1.1 on 2026-10-08 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flight", "0001_initial"),
        ("passenger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("seat_row_number", models.IntegerField()),
                ("seat_number", models.IntegerField()),
                (
                    "flights",
                    models.ManyToManyField(
                        blank=True, related_name="tickets", to="flight.flight"
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="passenger.passenger",
                    ),
                ),
            ],
        ),
    ]
