# Generated by Django 6.1.1 on 2026-10-08 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aircraft", "0001_initial"),
        ("airline", "0001_initial"),
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=5)),
                ("departure_time", models.TimeField()),
                ("arrival_time", models.TimeField()),
                (
                    "aircraft",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="aircraft.aircraft",
                    ),
                ),
                (
                    "airline",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airline.airline",
                    ),
                ),
                (
                    "destination_airport",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arriving_flights",
                        to="airport.airport",
                    ),
                ),
                (
                    "origin_airport",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="departing_flights",
                        to="airport.airport",
                    ),
                ),
            ],
        ),
    ]
