# Generated by Django 6.1.1 on 2026-10-08 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("booking", "0001_initial"),
        ("passenger", "0001_initial"),
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="passengers",
            field=models.ManyToManyField(
                related_name="passengers", to="passenger.passenger"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="tickets",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ticket.ticket",
            ),
        ),
    ]
